4155 embedded viewer query params
nulib/dc-nextjs pull request #294
Opened 2023-09-05 21:21 UTC by adamjarling

## What does this do?
Supports user control of displaying certain Clover `Viewer` elements for embedded players.   The user can supply query params at the end of the embedded URL, which will get picked up by the embedded player and communicated to Clover `Viewer`.

The following query params are supported:

For example:

2023-09-12 00:52 UTC, mathewjordan requested changes
Just a minor bug related to a value mismatch. Otherwise looks and works great.

2023-09-12 00:52 UTC, mathewjordan commented on components/Work/ActionsDialog/DownloadAndShare/EmbedViewer.tsx
> +      case "show closed":
```suggestion
      case "show default closed":
```

2023-09-12 00:52 UTC, mathewjordan commented on components/Work/ActionsDialog/DownloadAndShare/EmbedViewer.tsx
> +      case "show open":
```suggestion
      case "show default open":
```

2023-09-12 00:52 UTC, mathewjordan commented on components/Work/ActionsDialog/DownloadAndShare/EmbedViewer.tsx
> +      case "show open":
It looks like this was not matching the values set in the options.

2023-09-12 00:52 UTC, mathewjordan commented on components/Work/ActionsDialog/DownloadAndShare/EmbedViewer.tsx
> +      case "show closed":
Same as above.

2023-09-12 00:52 UTC, mathewjordan commented on pages/embedded-viewer/[manifestId].tsx
> +    showIIIFBadge: showIIIFBadge === "true" ? true : false,
What if we just set this to false since this isn't a customizable option. Might be a little less confusing to end users.
```suggestion
    showIIIFBadge: false,
```

2023-09-12 00:52 UTC, mathewjordan commented on pages/embedded-viewer/[manifestId].tsx
> +    showIIIFBadge = "true",
Or rather, maybe this should just be false as the default here?

2023-09-12 13:27 UTC, adamjarling commented
> Just a minor bug related to a value mismatch. Otherwise looks and works great.

Yea, would be pretty straight forward to do.  Was kinda testing the waters on whether this visual is even necessary, or clunky?   @davidschober any thoughts?

2023-09-12 13:28 UTC, adamjarling commented on components/Work/ActionsDialog/DownloadAndShare/DownloadAndShare.styled.ts
> +
Yea, would be pretty straight forward to do. Was kinda testing the waters on whether this visual is even necessary, or clunky? @davidschober any thoughts?

2023-09-12 19:39 UTC, adamjarling commented
@mathewjordan Updated with some clean up, simplifying the logic around what the user can actually configure in the UI.  And built in the 'real time' preview to match `select` element options.  And added a test to the main component here.

2023-09-13 12:56 UTC, mathewjordan approved these changes
Let's roll with it.

2023-09-13 13:28 UTC, merged