Grab form values in submit handler
nulib/dc-nextjs pull request #356
Opened 2024-07-26 17:58 UTC by adamjarling

2024-07-29 19:45 UTC, kdid requested changes
Code & flow of form looks 👍 

I'm not sure all need to be addressed right now, but here's some issues I'm seeing:

- Initially both thumbs up and down looked selected (maybe it's just me but the purple thumbs didn't look like something I was being invited to click - it confused me for a minute).
- I selected the checkbox to follow up with me but my email address was not submitted with the form payload
- I selected the thumbs up button but I'm still seeing only negative choices in the response options

2024-07-29 20:06 UTC, mathewjordan commented
> Code & flow of form looks 👍
> 
> I'm not sure all need to be addressed right now, but here's some issues I'm seeing:
> 
>     * Initially both thumbs up and down looked selected (maybe it's just me but the purple thumbs didn't look like something I was being invited to click - it confused me for a minute).
> 
>     * I selected the checkbox to follow up with me but my email address was not submitted with the form payload
> 
>     * I selected the thumbs up button but I'm still seeing only negative choices in the response options

Thank you!

For the third item, it looks like the `/auth/whoami` endpoint might be borked and isn't returning email correctly -- at least for my user. Can you help us verify somehow?

This is where we make the request before assigning the returned values to our UserProvider:
https://github.com/nulib/dc-nextjs/blob/deploy/staging/lib/user-helpers.ts#L7-L9

2024-07-29 21:26 UTC, kdid commented
Yeah, looks like the email is not currently coming back in the NUSSO response - looking into it.

2024-07-30 14:56 UTC, kdid approved these changes

2024-07-31 17:08 UTC, merged