Work page placeholder
nulib/dc-nextjs pull request #39
Opened 2022-05-25 16:24 UTC by adamjarling

## What does this do?

The Work page placeholder is now in place.  For incremental static regeneration (curious how this works when ends up in AWS), we're grabbing 100 works which will be statically generated at build time.  The other Work pages should dynamically build and be served ok.  We'll test it.

NOTE: there is a test warning that happens because of how we're importing a dynamic component (Clover IIIF, which pulls in OpenSeadragon, which only lives in the browser environment).  Will come back to how to mock either Clover or Openseadragon with a fresh head, or pair with @mathewjordan to sort it out.

### To test/view
Go to the Search page, and click on any work search result image.  

![image](https://user-images.githubusercontent.com/3020266/170312575-55e6cc1e-ec77-4ed0-941a-f95a35da9583.png)

2022-05-25 17:48 UTC, mathewjordan requested changes
Looks like a good start. My main questions are regarding how far we want to take this now. Do we want to do any of the manifest fetching and distilling down to Nectar in this spint? The only requested change is on the type for `Shared/Cart.test.tsx`

2022-05-25 17:48 UTC, mathewjordan commented on components/Work/TopInfo.tsx
> +        ))}
Title (label), Metadata (metadata), Description (summary)... etc will be Nectar, long-term, yeah? Do we want to bring that in now?

2022-05-25 17:48 UTC, mathewjordan commented on components/Shared/Cart.test.tsx
> +import { render, screen } from "@/test-utils";
Rename this `Card.test.tsx`?

2022-05-25 17:48 UTC, mathewjordan commented on pages/works/[id].tsx
> +          <WorkTopInfo work={work} />
Do we want to hand this `work` or the fetched response of `work.iiif_manifest`?

2022-05-25 19:20 UTC, adamjarling commented on components/Shared/Cart.test.tsx
> +import { render, screen } from "@/test-utils";
This is now fixed in the latest push

2022-05-25 20:23 UTC, mathewjordan approved these changes
I think this is good. Take or leave my suggestion on the `supplementalInfo` in Figure.

2022-05-25 20:23 UTC, mathewjordan commented on components/Shared/Card.tsx
>      </div>
Yeah, I like this better. Cards having Figures that is.

2022-05-25 20:23 UTC, mathewjordan commented on components/Figure/Figure.tsx
> +      <SupplementalInfo>{supplementalInfo}</SupplementalInfo>
This maybe should be: 
```jsx
{supplementalInfo && <SupplementalInfo>{supplementalInfo}</SupplementalInfo>}
```

2022-05-26 13:10 UTC, adamjarling commented on components/Work/TopInfo.tsx
> +        ))}
Pulling in Nectar in a new issue as chatted about.

2022-05-26 13:14 UTC, adamjarling commented on pages/works/[id].tsx
> +          <WorkTopInfo work={work} />
Yea, to be handled in a forthcoming issue, how to grab the IIIF data, where to store it and pass it into any IIIF aware components.

2022-05-26 13:17 UTC, merged