Show leading zeros on minutes in shared link expiration display
nulib/dc-nextjs pull request #393
Opened 2024-12-12 22:11 UTC by kdid

- Shared links are currently displaying minutes in the expiration without leading zeroes.
- This update will now display, for example: `1:06pm` instead of `1:6pm`

### Steps to Test

- create a shared link in Meadow when the hour is a single digit
- view the shared link in DC and verify correct display of expiration time

2024-12-13 15:48 UTC, mathewjordan requested changes
I think timezone might be an issue now (or always was). See my comment below:

2024-12-13 15:48 UTC, mathewjordan commented on lib/utils/date-helpers.test.ts
> +    expect(result).toBe("November 14, 2023, 1:14pm");
I'm getting:

```
formatDateLong › should format date correctly in long format

    expect(received).toBe(expected) // Object.is equality

    Expected: "November 14, 2023, 1:14pm"
    Received: "November 14, 2023, **8:14am"**
```

I think this might be related timezones and the `Z` in the date. Not sure how to best proceed here but I'm happy to sit with you to figure out your local tests.

2024-12-13 15:50 UTC, mathewjordan commented on lib/utils/date-helpers.test.ts
> +    expect(result).toBe("November 14, 2023, 1:14pm");
![image](https://github.com/user-attachments/assets/558e4ff1-f4c6-4dc7-ad0b-29f512ca868c)

2024-12-13 19:21 UTC, kdid commented on lib/utils/date-helpers.test.ts
> +    expect(result).toBe("November 14, 2023, 1:14pm");
@mathewjordan - updated to account for local time zones. The test is a little wonky but hopefully good enough.

2024-12-18 15:02 UTC, kdid commented
@mathewjordan - this is ready for a re-review.

2024-12-18 21:08 UTC, mathewjordan approved these changes
👍

2024-12-19 15:29 UTC, merged