3003 collection page baseline
nulib/dc-nextjs pull request #58
Opened 2022-07-22 15:43 UTC by adamjarling

## What does this do?
Creates a baseline placeholder for individual Collection page in our app.   Note all the data is stubbed and not coming from a real Collection record.

![image](https://user-images.githubusercontent.com/3020266/180473361-abfe5de5-829d-4567-adfe-691a89610091.png)

## How to test
- Go to a Work 
- Click on the Collection image to visit the page
- Bask in the beauty of the page

2022-07-29 14:17 UTC, mathewjordan requested changes
Just one small change where things reverted. Looks good otherwise and I think its a good start.

2022-07-29 14:17 UTC, mathewjordan commented on components/Shared/Card.tsx
> +  href?: string;
I like this pass through.

2022-07-29 14:17 UTC, mathewjordan commented on components/Work/TopInfo.tsx
> +          description="Foo bar oh my"
This somehow was reverted back to the **Ima Title**

```suggestion
          title={work.collection_title}
          description="Collection description"
```

2022-07-29 14:35 UTC, adamjarling commented on components/Work/TopInfo.tsx
> +          description="Foo bar oh my"
Good catch.  Changes now updated.

2022-07-29 14:48 UTC, mathewjordan approved these changes
🚀 Let's go.

2022-07-29 15:57 UTC, merged

2022-08-02 19:47 UTC, davidschober commented
![Screen Shot 2022-08-02 at 2 43 02 PM](https://user-images.githubusercontent.com/4803230/182460261-b6d2c38c-54c5-4f0c-a3df-7bc68f9e9823.png)


^^^ This part should be an overlay pinned to the bottom of every page on the site that a user can click "acknowledge" on . #2695